earthstar-project/willow-rs

Cargo.toml, data-model/Cargo.toml, data-model/src/lib.rs, data-model/src/path.rs
- Rename root `willow-data-model` directory to just `data-model` (imagining having willow-groupings, willow-wgps, willow-sideload, etc). Seems we can have this internally without changing the name of the crate.
- `data-model/src/data-model` seemed a bit redundant.
=> Reorganise workspace

data-model/src/entry.rs, data-model/src/grouping/area.rs, data-model/src/grouping/area_of_interest.rs, data-model/src/grouping/mod.rs, data-model/src/grouping/range.rs, data-model/src/grouping/range_3d.rs, data-model/src/parameters.rs, data-model/src/path.rs
- Added `Range3d` struct with `includes_entry` and `intersection` methods, `Default` impl.
- `Range::includes` no longer moves the value being tested for inclusion
- Add Clone trait bound to NamespaceId, SubspaceId, PayloadDigest
- Add `AreaSubspace` with `includes` and `intersection` methods
- Add `Area` with `full`, `subspace`, `includes_entry`, and `intersection` methods.
- Add `AreaOfInterest` with `intersection` method.
=> Range3d, Area, and AreaOfInterest

data-model/src/entry.rs, data-model/src/parameters.rs, fuzz/fuzz_targets/mc_is_authorised_write.rs, meadowcap/src/mc_authorisation_token.rs
Renames the `IsAuthorisedWrite` trait to `AuthorisationToken` for consistency with `NamespaceId` and other parameter friends.
=> Rename IsAuthorisedWrite trait to AuthorisationToken

data-model/src/entry.rs, data-model/src/grouping/area.rs, data-model/src/grouping/range.rs, data-model/src/grouping/range_3d.rs
Quick fix to the feature flags to make `willow-data-model` compile without the `dev` feature.
=> fix: feature flag arbitrary imports

data-model/src/encoding/bytes.rs, data-model/src/encoding/compact_width.rs, data-model/src/encoding/mod.rs, data-model/src/encoding/unsigned_int.rs, data-model/src/entry.rs, data-model/src/grouping/area_of_interest.rs, data-model/src/grouping/mod.rs, data-model/src/lib.rs, meadowcap/src/communal_capability.rs, meadowcap/src/lib.rs, meadowcap/src/mc_authorisation_token.rs, meadowcap/src/mc_capability.rs, meadowcap/src/mc_subspace_capability.rs, meadowcap/src/owned_capability.rs
Adds top-level crate documentation, adds documentation on type parameters, improves some documentation, fixes some doc linting issues, and of course adds logos to the docs too.
=> Willow data model + Meadowcap docs polishing

Cargo.lock, data-model/Cargo.toml, data-model/src/encoding/error.rs, data-model/src/encoding/relativity.rs, data-model/src/encoding/shared_buffers.rs, data-model/src/lib.rs, data-model/src/path.rs, earthstar/Cargo.toml, earthstar/src/cinn25519.rs, fuzz/Cargo.toml, fuzz/src/encode.rs, meadowcap/Cargo.toml
- Removes usage of `MaybeUnit` in path, 
- use `std::error::Error` instead of `core::error::Error`
- No longer use `uninit` flavoured ufotofu APIs
=> Make willow-data-model + meadowcap crates no longer require nightly channel

data-model/src/entry.rs, data-model/src/grouping/area_of_interest.rs, data-model/src/grouping/range.rs, data-model/src/grouping/range_3d.rs, fuzz/fuzz_targets/mc_is_authorised_write.rs, meadowcap/src/communal_capability.rs, meadowcap/src/lib.rs, meadowcap/src/mc_authorisation_token.rs, meadowcap/src/mc_capability.rs, meadowcap/src/mc_subspace_capability.rs, meadowcap/src/owned_capability.rs
This PR contains changes I made to willow-rs while porting iroh-willow to use willow-rs.
The changes are mostly small and not all related to each other. They were mostly done by doing jump to definition from iroh-willow when touching willow-rs parts that didn't fit in well yet.
I will add review comments in the diff to explain the motivation.
My idea was to submit this here, let you review it, and if anything warrants further discussion, I will separate it out into its own PR, to keep only uncontroversial things in here that can easily be merged.
If you prefer to split this up right away, let me know.
=> refactor: changes done while porting iroh-willow

.github/workflows/rust.yml, data-model/src/relative_encodings.rs, earthstar/src/lib.rs, encoding/src/bytes.rs, encoding/src/max_power.rs, meadowcap/src/mc_capability.rs, meadowcap/src/mc_subspace_capability.rs, rust-toolchain.toml
This adds more CI workflows (adapted from iroh):
* Build and test on mac OS
* Build and test on windows
* Build and test on android (aarch64 and armv7)
* Cross-compile and test on i686 (32bit) linux, armv7 linux, aarch64 linux
* Run `cargo fmt` and `cargo clippy` checks
* Use nextest for running tests (runs test in parallel, much faster)
* Runs only fuzz tests on nightly, all others on stable
apart from the CI workflow this
* fixes build failures on 32bit systems by using u64 not usize in more places
* tries to fix some unused import warnings wrt syncify (but failed, added an allow - will have to be revisited)
All green now!
=> chore/fix: add CI for more platforms and targets, fix build error on 32bit systems

data-model/src/lengthy_entry.rs, data-model/src/store.rs
Adds query trait methods as detailed in https://github.com/earthstar-project/willow-rs/pull/21#issuecomment-2199568852:
> - query
>     - query entry by pair of path and subspace id
>       - yields Entry, AuthorisationToken, available payload prefix (length)
>       - option to filter out results with incomplete payloads
>     - query entries by area (of interest)
>       - all of the functionality of singleton queries, also
>       - ordering results (arbitrary, PTS (optionally reversed), TSP (optionally reversed), SPT (optionally reversed)) (?)
>     - subscriptions: all queries should also work as long-lived subscriptions
>       - this includes subscription to payload prefix appending
>       - this also includes notifications about overwriting and forgetting things
>     - …
=> Add query methods to Store trait

data-model/src/lengthy_entry.rs, data-model/src/lib.rs, data-model/src/store.rs
Work in progress, currently being discussed and iterated upon.
=> Store trait

Cargo.lock, wgps/Cargo.toml, wgps/src/lib.rs, wgps/src/ready_transport.rs
A small function for intercepting the first few bytes of a WGPS session in order to return the session's maximum payload size, received commitment, and transport set to immediately start returning encoded WGPS messages.
=> WGPS: Add ReadyTransport and friends

Cargo.lock, lcmux/Cargo.toml, lcmux/src/frames.rs
- Implements `Encodable` for LCMUX header messages
- Implements `Decodable` for `IncomingFragmentHeader`
=> Lcmux message codec

lcmux/src/frames.rs
Addresses the unaddressed comments in https://github.com/earthstar-project/willow-rs/pull/65#pullrequestreview-2500293361
=> Lil' fixes

wb_async_utils/src/lib.rs, wb_async_utils/src/mutex.rs, wb_async_utils/src/once_cell.rs, wb_async_utils/src/rw.rs, wb_async_utils/src/spsc.rs, wb_async_utils/src/take_cell.rs
Adds basic doc tests to the wb_async_utils crate, and changes the implementation of the utils from using UnsafeCell to using FairlyUnsafeCell.
=> wb_async_utils cleanup

Cargo.lock, fuzz/fuzz_targets/enc_mccapability_rel_area.rs, fuzz/fuzz_targets/mc_is_authorised_write.rs, fuzz/src/placeholder_params.rs, fuzz/src/silly_sigs.rs, meadowcap/Cargo.toml, meadowcap/src/communal_capability.rs, meadowcap/src/mc_authorisation_token.rs, meadowcap/src/mc_capability.rs, meadowcap/src/mc_subspace_capability.rs, meadowcap/src/owned_capability.rs, ufotofu_codec/src/proptest.rs, ufotofu_codec/src/proptest/relative.rs
Implements all the todos we had in Meadowcap after the move to ufotofu_codec. Now all encoding operations (e.g. for creating messages to sign) happen in single allocations.
=> Meadowcap + ufotofu_codec

data-model/src/store.rs, fuzz/src/lib.rs, fuzz/src/store.rs, store_simple_sled/src/lib.rs
This turns your implementation of `bulk_ingest_entry` on the simple sled store into a default method of the `Store` trait.
To do so without introducing some `: Clone` bounds, I simplified the return type. There errors are not paired with the authorised entry which raised them, instead the caller should match errors to entries based on the order in which they are emitted. Does that work for you? The alternative - gating implementation of bulk ingestion behind Clone bounds - felt a bit awkward to me.
=> Make bulk_ingest_entry a default method

data-model/src/grouping/area.rs, data-model/src/store.rs, fuzz/src/store.rs, store_simple_sled/src/lib.rs, wb_async_utils/src/spsc.rs
Allows spsc receivers and senders to query whether the other endpoint has been dropped already. Also includes some store trait changes we discussed.
=> Misc refactors

Cargo.lock, data-model/src/entry.rs, data-model/src/grouping/area.rs, data-model/src/grouping/area_of_interest.rs, data-model/src/grouping/range.rs, data-model/src/grouping/range_3d.rs, data-model/src/lengthy_entry.rs, data-model/src/parameters.rs, data-model/src/store.rs, fuzz/Cargo.toml, fuzz/src/store.rs, lcmux/Cargo.toml, lcmux/src/server_logic.rs, store_simple_sled/Cargo.toml, store_simple_sled/src/lib.rs, wb_async_utils/Cargo.toml, wgps/Cargo.toml
- Add `Clone` to `AuthorisationToken`
- Refactor `StoreEvent` to not be full of horrible tuples, but horrible structs instead
- Add `origin` param to `Store#ingest_entry`
- Removed `order` param for `Store#query_area`
- Implement `StoreSimpleSled#new` and `StoreSimpleSled#from_existing`
- Send events when things happen in the store.
- Fix bugs in `StoreSimpleSled#append_payload`
- Interpret `QueryIgnoreParams` the way they are meant to be interpreted.
- Make error conversion a *bit* nicer
=> Event subscriptions in StoreSimpleSled

Cargo.lock, data-model/src/grouping/area.rs, data-model/src/lib.rs, fuzz/fuzz_targets/enc_mccapability_rel_area.rs, fuzz/fuzz_targets/store.rs, fuzz/src/placeholder_params.rs, meadowcap/src/communal_capability.rs, meadowcap/src/mc_capability.rs, meadowcap/src/owned_capability.rs, store_simple_sled/src/lib.rs, willow_25/Cargo.toml, willow_25/src/authorisation_token.rs, willow_25/src/signature.rs
Wanted these for situations where you can decode items which you trust are valid (e.g. a verifiable signature) beforehand (e.g. because you encoded the data yourself).
Concrete use case being decoding authorisation tokens from a sled store without validating all their signatures each time.
=> TrustedDecodable + RelativeTrustedDecodable traits

data-model/src/path/mod.rs
Tackling part of https://github.com/earthstar-project/willow-rs/issues/56
I went with `Path::from_slices` rather than separate `Path::from_{bytes,strs}` because I didn't want to duplicate the logic, but there wasn't really a clean way to implement one in terms of another because even though `&str` can dereference to `&[u8]`, it's not possible to convert `&[&str]` to `&[&[u8]]` without allocating or transmuting (as far as I could see).
I saw that other methods have a `#### Complexity` section but I didn't feel confident in determining what the total complexity was because I can't quite tell how `append_component` behaves (complexity-speaking).
Also let me know if or where the best place to add a unit test for this would be!
I'm running late for something so I'll drop this and check back …
=> Add Path::from_slices helper function

data-model/src/store.rs, fuzz/src/store.rs, fuzz/src/store_events.rs, store_simple_sled/src/lib.rs
- Adds `Payload` enum with complete and incomplete variants
- Returns this enum from `Store.payload`
- Update StoreSimpleSled and ControlStore to satisfy trait
- Update testing tools to handle variants
=> Store.payload returns Payload enum

data-model/src/grouping/area.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/area_map.rs, fuzz/fuzz_targets/namespaced_area_map.rs
Two new structs which allow you to store anything relative to an area, and then query back any stored things which intersect with a given area.
- AreaMap stores every item with a value of `T` along with an `Area`
- NamespacedAreaMap stores every item with a value of `T` along with an `Area` *and* `NamespaceId`.
=> AreaMap + NamespaceAreaMap

Cargo.lock, Cargo.toml, data-model/Cargo.toml, data-model/src/parameters.rs, encoding/Cargo.toml, fuzz/Cargo.toml, lcmux/Cargo.toml, lcmux/src/client_logic.rs, lcmux/src/server_logic.rs, lcmux/src/session.rs, meadowcap/Cargo.toml, pio/Cargo.toml, pio/src/area.rs, pio/src/personal_private_interest.rs, store_simple_sled/Cargo.toml, transport_encryption/Cargo.toml, wgps/Cargo.toml, wgps/src/lib.rs, wgps/src/pio/capable_aois.rs, wgps/src/pio/mod.rs, wgps/src/pio/salted_hashes.rs, willow_25/Cargo.toml, willow_test_vectors/Cargo.toml
Removes trait bounds from types, and simplifies a couple of references to opaque state objects by hardcoding them to RCs instead.
=> Generics refactor
